dist: precise
sudo: required
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
env: CC=gcc
matrix:
  allow_failures:
    - php: nightly
    - php: 7.0
  include:
    - php: 7.0
      env: CC=clang
    - php: 7.1
      env: CC=clang
    - php: 7.2
      env: CC=clang
addons:
  apt:
    packages: clang
before_install:
  - cd extension/src
  - phpize
  - ./configure
  - make
  - cd ../../
install:
  - cd extension/src
  - make install
  - cd ../../
before_script:
   - composer install --prefer-source --no-interaction --working-dir ./library
   - echo 'extension = checkout.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
   - vendor/bin/phpspec run
   - php --ri checkout
